# -*- mode: markdown ; -*-

# Orriaren datuak

name: Ogibero
description: Errezeta askeak
author: Ondiz Zarraga

# Idazteko konfigurazioa

markdown: kramdown

# Erabilitako gemak

gems:
- jekyll-feed
